apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: MetalMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-metal
    app.kubernetes.io/managed-by: kustomize
  name: metalmachinetemplate-sample-control-plane
spec:
  template:
    spec:
      serverSelector:
        matchLabels:
          server: metal
